name: Pulumi Deploy Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  # Determine which tenants were modified
  get-changed-tenants:
    runs-on: ubuntu-latest
    outputs:
      tenants: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/filters.yml

  deploy:
    runs-on: ubuntu-latest
    needs: get-changed-tenants

    permissions:
      contents: read
      id-token: write

    # Run this job for each modified tenant
    strategy:
      fail-fast: false
      matrix:
        # List of tenants from get-changed-tenants step
        tenant: ${{ fromJson(needs.get-changed-tenants.outputs.tenants) }}

    environment: ${{ matrix.tenant }}-staging

    # Don't allow concurrent deploys
    concurrency:
      group: ${{ matrix.tenant }}-staging-deploy
      # Deployments will be queued
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: '0.8.9'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Preview changes
        uses: pulumi/actions@v6
        env:
          # ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.PULUMI_AZURE_STORAGE_ACCOUNT }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_ENCRYPTION_KEY }}
        with:
          command: preview
          work-dir: infra/${{ matrix.tenant }}
          stack-name: staging
          cloud-url: azblob://${{ secrets.PULUMI_AZURE_CONTAINER }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-pr: true
          upsert: true

      - name: Deploy changes
        uses: pulumi/actions@v6
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.PULUMI_AZURE_STORAGE_ACCOUNT }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_ENCRYPTION_KEY }}
          TENANT_IDENTIFIER_ENV_VAR: ${{ secrets.TENANT_IDENTIFIER }}
          MANAGED_IDENTITY_RESOURCE_GROUP_ENV_VAR: ${{ secrets.MANAGED_IDENTITY_RESOURCE_GROUP }}
          MANAGED_IDENTITY_NAME_ENV_VAR: ${{ secrets.MANAGED_IDENTITY_NAME }}
          SERVICE_PRINCIPAL_OBJECT_ID_ENV_VAR: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}
        with:
          command: up
          work-dir: infra/${{ matrix.tenant }}
          stack-name: staging
          cloud-url: azblob://${{ secrets.PULUMI_AZURE_CONTAINER }}
